#!/bin/sh

set -e

OPTIONS="$@"
FILTERED_OPTIONS=

# Don't know if filtering op the options is really necessary
# but do it just in case
until [ -z "$1" ] 
do
  case "$1" in
      "-a"|"-s"|"-i"|"-p*"|"--package=*"|"-N*"|"--no-package=*")
	  ;;
      *)
	  FILTERED_OPTIONS="$FILTERED_OPTIONS $1"
	  ;;
  esac
  shift
done

for p in `dh_listpackages "$OPTIONS"` ; do
    dh_haskell_build --package=$p $FILTERED_OPTIONS
    dh_haskell_install  --package=$p $FILTERED_OPTIONS
done	

