Document: haskell-devscripts
Title: Debian haskell-devscripts Manual
Author: <insert document author here>
Abstract: This manual describes what haskell-devscripts is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/haskell-devscripts/haskell-devscripts.sgml.gz

Format: postscript
Files: /usr/share/doc/haskell-devscripts/haskell-devscripts.ps.gz

Format: text
Files: /usr/share/doc/haskell-devscripts/haskell-devscripts.text.gz

Format: HTML
Index: /usr/share/doc/haskell-devscripts/html/index.html
Files: /usr/share/doc/haskell-devscripts/html/*.html

  
